development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 02f16cbc5b6637d12f8ab376625b2c4a61e12d82f51fb4a51f2df726cef219c6e6469ce2c56f724c4d26c1cbe04e12377c41adf783049234d2431fab82728809

test:
  domain_name: example.com
  secret_key_base: c60f3d4ebf69e3da5e59f597f8808e84edadea4c306bdeab1601b51a5f24706fd309f86dfae43708fed02ccc2e3cec2e0e9c9240e2f09fd313676eddad351519

production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
